from enum import IntEnum
from fastapi import status as HTTP_STATUS


class Code(IntEnum):
    SUCCESS = HTTP_STATUS.HTTP_200_OK

    # Client Errors
    BAD_REQUEST = HTTP_STATUS.HTTP_400_BAD_REQUEST
    UNAUTHORIZED = HTTP_STATUS.HTTP_401_UNAUTHORIZED
    FORBIDDEN = HTTP_STATUS.HTTP_403_FORBIDDEN
    NOT_FOUND = HTTP_STATUS.HTTP_404_NOT_FOUND

    # Server Errors
    INTERNAL_ERROR = HTTP_STATUS.HTTP_500_INTERNAL_SERVER_ERROR
    NOT_IMPLEMENTED = HTTP_STATUS.HTTP_501_NOT_IMPLEMENTED
    SERVICE_UNAVAILABLE = HTTP_STATUS.HTTP_503_SERVICE_UNAVAILABLE
